apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
  finalizers:
    - service.k8s.alibaba/resources
  name: pgvector
  namespace: u-ai
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 192.168.3.58
  clusterIPs:
    - 192.168.3.58
  externalTrafficPolicy: Local
  healthCheckNodePort: 32034
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: pgvector
      nodePort: 31242
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: pgvector
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 47.96.70.125
